# NumPy入門


In [1]:
import numpy as np

In [4]:
x = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
print(x)

[1. 2. 3. 4. 5.]


In [6]:
x = np.array([1,2,3])
print(x)
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


In [7]:
my_list1 = [1,2,3,4,5]
my_array1 = np.array(my_list1)

In [8]:
my_list2 = [10,20,30,40,50]
my_lists = [my_list1, my_list2]
my_lists

[[1, 2, 3, 4, 5], [10, 20, 30, 40, 50]]

In [9]:
my_array2 = np.array(my_lists)
my_array2

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [10]:
# 次のように、タプルを複数渡すとエラーになってしまいます。
np.array((1,2,3),(4,5,6))

TypeError: data type not understood

In [11]:
a = np.array([1,2,3,4])
a.shape

(4,)

In [12]:
b = np.array([[1,2],[3,4]])
b.shape

(2, 2)

In [13]:
x = np.array(10)
print(x)

10


In [15]:
x = np.arange(1,10).reshape(3,3)
y = np.arange(1,10).reshape(3,3)
"""
xを下記のように書き換えることも可能
x = np.reshape(x, (3,3))
"""
print(x)
print(y)

print(x + y)
print(x - y)
print(x * y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [17]:
sample_array = np.arange(10)
print(sample_array)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
sample_array2 = sample_array.reshape(2,5)
print(sample_array2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [22]:
# concatenateを使って、データの結合する(axisで行方向か、縦方向を指定可能)
sample_array3 = np.array([[1,2,3],[4,5,6]])
sample_array4 = np.array([[7,8,9],[10,11,12]])

In [27]:
print(np.concatenate([sample_array3, sample_array4],axis=1))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [24]:
print(np.hstack((sample_array3, sample_array4)))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


"""
axis=0で列方向
axis=1で行方向です。
下記URLを参考ください。
https://qiita.com/shuetsu@github/items/2bf8bba233c5ecc7a0ad
"""

In [29]:
print(np.concatenate([sample_array3,sample_array4],axis=0))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [30]:
print(np.vstack((sample_array3,sample_array4)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [31]:
sample_array = np.arange(10)
print(sample_array)

[0 1 2 3 4 5 6 7 8 9]


In [32]:
print(sample_array + 5)

[ 5  6  7  8  9 10 11 12 13 14]


In [33]:
n1 = np.array([1,2,3,4,5])
print(n1)

[1 2 3 4 5]


In [35]:
# 配列の次元数は np.ndim() 関数で取得可能
np.ndim(n1) # 1 -> 1次元

1

In [37]:
n1.shape

(5,)

In [39]:
n2 = np.array([[1,2],[3,4],[5,6]])
print(n2)
print(n2.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


In [40]:
my_li1 = [-1,4]

my_li2 = [3,2]

my_li3 = [2,5]

my_li4 = [0,1]

my_lists = [my_li1,my_li2,my_li3,my_li4]

my_array3 = np.array(my_lists)

my_array3

array([[-1,  4],
       [ 3,  2],
       [ 2,  5],
       [ 0,  1]])